# Generated by Django 5.1.1 on 2024-10-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_teachers_student_teacher_alter_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
